version: '3.7'

services:

  mongo:
    image: mongo:5.0.11
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo:/data/db

volumes:
  mongo: